version: '2.2'
services:

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

#  api:
#    image: sample-express-app
#    build: .
#    networks:
#      - backend
#    ports:
#      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /Users/paulinegc/WebstormProjects/popo-mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

networks:
  backend:
    driver: bridge
